export const ROUTES_NAMES = {
	collecte: ['collecte', 'CollecteNext','collecteKN', 'collecteKnBloc', 'CollectKnEnd','UnexpectedCollecte','CollecteVerif'],
	programmation: ['Programmation', 'CollectesByType', 'EditCollecte', 'NewCollecte'],
	consultation: ['consultation',
				'consultationFormulaire',
				'consultationCollecte',
				'consultationForm',
				'consultationFormList',
				'consultationFormCollecte',
				'consultationProjet',
				'consultationProjetList',
				'consultationProjetCollecte',
				'newCollecte'
				],
	habilitation: ['Habilitation',
				'HabilitationHabilitation',
				'habilitationByHab',
				'NewCollecteVeille'],
	operateur: ['Operateur',
				'habilitationByAgent',
				'HabilitationAgent',
				'ControlHistory',
				'ControlView'],
	statistiques: ['Statistiques','NewRequest'],
	home: ['Home'],
};
