export const ROUTES_NAMES = {
	collecte: ['collecte', 'CollecteNext','collecteKN', 'collecteKnBloc', 'CollectKnEnd','UnexpectedCollecte','CollecteVerif'],
	programmation: ['Programmation', 'CollectesByType', 'EditCollecte', 'NewCollecte'],
	consultation: ['consultation',
				'consultationFormulaire',
				'consultationCollecte',
				'consultationForm',
				'consultationFormList',
				'consultationFormCollecte',
				'consultationProjet',
				'consultationProjetList',
				'consultationProjetCollecte',
				'newCollecte',
				'consultationKnWtBcl',
				'consultationKnWtBclList',
				'consultationSsOperateur',
				'consultationSsOperateurList',
				'consultationSsControleur',
				'consultationSsControleurList',
				'consultationOperateur',
				'consultationOperateurList',
				'consultationControleur',
				'consultationControleurList',
				'consultationCollecteOptionsOperateur',
				'consultationCollecteOptionsControleur',
				'consultationKndeKn',
				'consultationKndeKnList'

				],
	habilitation: ['Habilitation',
				'HabilitationPersonnel',
				'HabilitationPersonnelStatus',
				'HabilitationHabilitation',
				'habilitationByHab',
				'NewCollecteVeille'],
	operateur: ['Operateur',
				'habilitationByAgent',
				'HabilitationAgent',
				'ControlHistory',
				'ControlView'],
	statistiques: ['Statistiques','NewRequest'],
	home: ['Home'],
	echeancier: ['Echeancier']
};
